name: GCC on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install gnuplot
      run: |
        sudo apt-get update
        sudo apt-get install -y gnuplot
    - name: run-cmake
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        configurationRegexFilter: .*
        buildDirectory: "${{ github.workspace }}/build"
    - name: run debug build
      run: ${{ github.workspace }}/build/x64-Debug/examples/examples
    - name: copy result files of debug build
      run: >-
        mkdir -p gcc_on_ubuntu/debug &&
        cp *.png *.txt ./gcc_on_ubuntu/debug
    - name: run release build
      run: ${{ github.workspace }}/build/x64-Release/examples/examples
    - name: copy result files of release build
      run: >-
        mkdir -p gcc_on_ubuntu/release &&
        cp *.png *.txt ./gcc_on_ubuntu/release
    - name: upload result files
      uses: actions/upload-artifact@v1
      with:
        name: gcc_on_ubuntu_${{ github.sha }}
        path: gcc_on_ubuntu